/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhopizzaria;

import java.io.IOException;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
//
/**
 *
 * @author Guilherme
 */
public class MainFrame extends javax.swing.JFrame {
    
    ClienteTableModel modeloTabelaCliente;
    SaboresTableModel modeloTabelaSabores;
    /**
     * Creates new form testJframe
     * @throws java.io.IOException
     */
    public MainFrame() throws IOException {
        modeloTabelaCliente = new ClienteTableModel();

        modeloTabelaSabores = new SaboresTableModel();


        initComponents();
        try {
            // TODO add your handling code here:
            TipoPizzaDAO dao = new TipoPizzaDAO();
            valorPizzaSimples.setText(String.valueOf(dao.findValorByTipo(1)));
            valorPizzaEspecial.setText(String.valueOf(dao.findValorByTipo(2)));
            valorPizzaPremium.setText(String.valueOf(dao.findValorByTipo(3)));
            
            
        } catch (SQLException | IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogNovoCliente = new javax.swing.JDialog();
        labelNomeCliente = new javax.swing.JLabel();
        fieldNomeCliente = new javax.swing.JTextField();
        labelTelefoneCliente = new javax.swing.JLabel();
        labelRuaCliente = new javax.swing.JLabel();
        labelNumeroCliente = new javax.swing.JLabel();
        fieldRuaCliente = new javax.swing.JTextField();
        labelBairroCliente = new javax.swing.JLabel();
        labelCidadeCliente = new javax.swing.JLabel();
        fieldBairroCliente = new javax.swing.JTextField();
        fieldCidadeCliente = new javax.swing.JTextField();
        labelComplementoCliente = new javax.swing.JLabel();
        fieldComplementoCliente = new javax.swing.JTextField();
        btnGravarNovoCliente = new javax.swing.JButton();
        btnCancelarNovoCliente = new javax.swing.JButton();
        fieldNumeroCliente = new javax.swing.JTextField();
        fieldTelefoneCliente = new javax.swing.JTextField();
        dialogEditarCliente = new javax.swing.JDialog();
        labelNomeCliente1 = new javax.swing.JLabel();
        fieldNomeClienteEditar = new javax.swing.JTextField();
        labelTelefoneCliente1 = new javax.swing.JLabel();
        labelRuaCliente1 = new javax.swing.JLabel();
        labelNumeroCliente1 = new javax.swing.JLabel();
        fieldRuaClienteEditar = new javax.swing.JTextField();
        labelBairroCliente1 = new javax.swing.JLabel();
        labelCidadeCliente1 = new javax.swing.JLabel();
        fieldBairroClienteEditar = new javax.swing.JTextField();
        fieldCidadeClienteEditar = new javax.swing.JTextField();
        labelComplementoCliente1 = new javax.swing.JLabel();
        fieldComplementoClienteEditar = new javax.swing.JTextField();
        btnGravarEditarCliente = new javax.swing.JButton();
        btnCancelarEditarCliente = new javax.swing.JButton();
        fieldNumeroClienteEditar = new javax.swing.JTextField();
        fieldTelefoneClienteEditar = new javax.swing.JTextField();
        dialogNovoSabor = new javax.swing.JDialog();
        fieldNomeSabor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGravarSabor = new javax.swing.JButton();
        fieldTipoSabor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        fieldIngredientesSabor = new javax.swing.JTextArea();
        dialogValores = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        abaPedidos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnNovoSabor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        btnNovoCliente = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        searchClienteField = new javax.swing.JTextField();
        btnSearchCliente = new javax.swing.JButton();
        btnClearFilterCliente = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorPizzaEspecial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorPizzaPremium = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGravarValores = new javax.swing.JButton();
        valorPizzaSimples = new javax.swing.JTextField();

        dialogNovoCliente.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogNovoCliente.setTitle("Novo Cliente");
        dialogNovoCliente.setMinimumSize(new java.awt.Dimension(400, 314));
        dialogNovoCliente.setModal(true);
        dialogNovoCliente.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogNovoCliente.setName("novoCliente"); // NOI18N
        dialogNovoCliente.setResizable(false);

        labelNomeCliente.setText("Nome");

        fieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeClienteActionPerformed(evt);
            }
        });

        labelTelefoneCliente.setText("Telefone");

        labelRuaCliente.setText("Rua");

        labelNumeroCliente.setText("Número");

        fieldRuaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRuaClienteActionPerformed(evt);
            }
        });

        labelBairroCliente.setText("Bairro");

        labelCidadeCliente.setText("Cidade");

        labelComplementoCliente.setText("Complemento");

        btnGravarNovoCliente.setText("GRAVAR");
        btnGravarNovoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarNovoClienteMouseClicked(evt);
            }
        });
        btnGravarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarNovoClienteActionPerformed(evt);
            }
        });

        btnCancelarNovoCliente.setText("CANCELAR");
        btnCancelarNovoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarNovoClienteMouseClicked(evt);
            }
        });
        btnCancelarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNovoClienteActionPerformed(evt);
            }
        });

        fieldNumeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogNovoClienteLayout = new javax.swing.GroupLayout(dialogNovoCliente.getContentPane());
        dialogNovoCliente.getContentPane().setLayout(dialogNovoClienteLayout);
        dialogNovoClienteLayout.setHorizontalGroup(
            dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                        .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fieldRuaCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(fieldNomeCliente, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(labelBairroCliente)
                                    .addComponent(labelNomeCliente))
                                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelCidadeCliente)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldTelefoneCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelNumeroCliente)
                                                    .addComponent(fieldNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                                        .addComponent(labelComplementoCliente)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(fieldComplementoCliente)))
                                            .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                                .addComponent(labelTelefoneCliente)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                .addComponent(labelRuaCliente)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                        .addComponent(fieldBairroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                                .addComponent(btnGravarNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarNovoCliente))
                            .addComponent(fieldCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        dialogNovoClienteLayout.setVerticalGroup(
            dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNovoClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCliente)
                    .addComponent(labelTelefoneCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRuaCliente)
                    .addComponent(labelNumeroCliente)
                    .addComponent(labelComplementoCliente))
                .addGap(3, 3, 3)
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRuaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldComplementoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBairroCliente)
                    .addComponent(labelCidadeCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(dialogNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarNovoCliente)
                    .addComponent(btnCancelarNovoCliente))
                .addContainerGap())
        );

        dialogNovoCliente.getAccessibleContext().setAccessibleParent(btnNovoCliente);

        dialogEditarCliente.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogEditarCliente.setTitle("Editar dados de Cliente");
        dialogEditarCliente.setMinimumSize(new java.awt.Dimension(400, 314));
        dialogEditarCliente.setModal(true);
        dialogEditarCliente.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogEditarCliente.setName("novoCliente"); // NOI18N
        dialogEditarCliente.setResizable(false);

        labelNomeCliente1.setText("Nome");

        fieldNomeClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeClienteEditarActionPerformed(evt);
            }
        });

        labelTelefoneCliente1.setText("Telefone");

        labelRuaCliente1.setText("Rua");

        labelNumeroCliente1.setText("Número");

        fieldRuaClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRuaClienteEditarActionPerformed(evt);
            }
        });

        labelBairroCliente1.setText("Bairro");

        labelCidadeCliente1.setText("Cidade");

        labelComplementoCliente1.setText("Complemento");

        btnGravarEditarCliente.setText("GRAVAR");
        btnGravarEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarEditarClienteMouseClicked(evt);
            }
        });
        btnGravarEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarEditarClienteActionPerformed(evt);
            }
        });

        btnCancelarEditarCliente.setText("CANCELAR");
        btnCancelarEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEditarClienteMouseClicked(evt);
            }
        });
        btnCancelarEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarClienteActionPerformed(evt);
            }
        });

        fieldNumeroClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroClienteEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogEditarClienteLayout = new javax.swing.GroupLayout(dialogEditarCliente.getContentPane());
        dialogEditarCliente.getContentPane().setLayout(dialogEditarClienteLayout);
        dialogEditarClienteLayout.setHorizontalGroup(
            dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                        .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fieldRuaClienteEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(fieldNomeClienteEditar, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(labelBairroCliente1)
                                    .addComponent(labelNomeCliente1))
                                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelCidadeCliente1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldTelefoneClienteEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelNumeroCliente1)
                                                    .addComponent(fieldNumeroClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                                        .addComponent(labelComplementoCliente1)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(fieldComplementoClienteEditar)))
                                            .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                                .addComponent(labelTelefoneCliente1)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                .addComponent(labelRuaCliente1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                        .addComponent(fieldBairroClienteEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                                .addComponent(btnGravarEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarEditarCliente))
                            .addComponent(fieldCidadeClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        dialogEditarClienteLayout.setVerticalGroup(
            dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEditarClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCliente1)
                    .addComponent(labelTelefoneCliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomeClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefoneClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRuaCliente1)
                    .addComponent(labelNumeroCliente1)
                    .addComponent(labelComplementoCliente1))
                .addGap(3, 3, 3)
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRuaClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldComplementoClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNumeroClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBairroCliente1)
                    .addComponent(labelCidadeCliente1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBairroClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCidadeClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(dialogEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarEditarCliente)
                    .addComponent(btnCancelarEditarCliente))
                .addContainerGap())
        );

        dialogNovoSabor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogNovoSabor.setTitle("Cadastrar Novo Sabor");
        dialogNovoSabor.setMinimumSize(new java.awt.Dimension(410, 319));
        dialogNovoSabor.setModal(true);
        dialogNovoSabor.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogNovoSabor.setPreferredSize(new java.awt.Dimension(410, 319));
        dialogNovoSabor.setResizable(false);

        fieldNomeSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeSaborActionPerformed(evt);
            }
        });

        jLabel5.setText("Sabor:");

        btnGravarSabor.setText("Adicionar");
        btnGravarSabor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarSaborMouseClicked(evt);
            }
        });
        btnGravarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarSaborActionPerformed(evt);
            }
        });

        fieldTipoSabor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simples", "Especial", "Premium" }));
        fieldTipoSabor.setToolTipText("");
        fieldTipoSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTipoSaborActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo:");

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setText("Ingredientes:");

        fieldIngredientesSabor.setColumns(20);
        fieldIngredientesSabor.setRows(5);
        jScrollPane4.setViewportView(fieldIngredientesSabor);

        javax.swing.GroupLayout dialogNovoSaborLayout = new javax.swing.GroupLayout(dialogNovoSabor.getContentPane());
        dialogNovoSabor.getContentPane().setLayout(dialogNovoSaborLayout);
        dialogNovoSaborLayout.setHorizontalGroup(
            dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNovoSaborLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dialogNovoSaborLayout.createSequentialGroup()
                        .addComponent(btnGravarSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addComponent(fieldNomeSabor)
                    .addComponent(fieldTipoSabor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE))
        );
        dialogNovoSaborLayout.setVerticalGroup(
            dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNovoSaborLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomeSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogNovoSaborLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldTipoSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(dialogNovoSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarSabor)
                    .addComponent(jButton7))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogValoresLayout = new javax.swing.GroupLayout(dialogValores.getContentPane());
        dialogValores.getContentPane().setLayout(dialogValoresLayout);
        dialogValoresLayout.setHorizontalGroup(
            dialogValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogValoresLayout.setVerticalGroup(
            dialogValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria LPOO");
        setIconImages(null);

        abaPedidos.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        abaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaPedidosMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Data Hora", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Novo Pedido");

        jButton2.setText("Visualizar");

        jButton3.setText("Editar");

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abaPedidos.addTab("Pedidos", jPanel1);

        jTable3.setModel(modeloTabelaSabores);
        jScrollPane3.setViewportView(jTable3);

        btnNovoSabor.setText("Novo Sabor");
        btnNovoSabor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoSaborMouseClicked(evt);
            }
        });
        btnNovoSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoSaborActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnNovoSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoSabor)
                .addGap(18, 18, 18))
        );

        abaPedidos.addTab("Sabores", jPanel5);

        tabelaClientes.setModel(modeloTabelaCliente);
        tabelaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaClientes);

        btnNovoCliente.setText("Novo Cliente");
        btnNovoCliente.setPreferredSize(new java.awt.Dimension(93, 27));
        btnNovoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoClienteMouseClicked(evt);
            }
        });
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        jButton6.setText("Editar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        searchClienteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClienteFieldActionPerformed(evt);
            }
        });

        btnSearchCliente.setText("Pesquisar");
        btnSearchCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClienteActionPerformed(evt);
            }
        });

        btnClearFilterCliente.setText("Limpar Filtro");
        btnClearFilterCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilterClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(searchClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClearFilterCliente))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClearFilterCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchClienteField, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnSearchCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        abaPedidos.addTab("Clientes", jPanel4);

        jLabel1.setText("Preços dos tipos de pizza");

        jLabel2.setText("Simples");

        jLabel3.setText("Especial");

        jLabel4.setText("Premium");

        btnGravarValores.setText("Gravar");
        btnGravarValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarValoresActionPerformed(evt);
            }
        });

        valorPizzaSimples.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorPizzaSimplesKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGravarValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorPizzaEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorPizzaPremium, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorPizzaSimples))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorPizzaSimples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorPizzaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(valorPizzaPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnGravarValores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        abaPedidos.addTab("Configurações", jPanel6);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1.setLayer(abaPedidos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        abaPedidos.getAccessibleContext().setAccessibleParent(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
      
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        // TODO add your handling code here:
       
        int linha = tabelaClientes.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione um cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            int x = JOptionPane.showConfirmDialog(this,"Confirma Exclusão do Cliente? todos os seus pedidos também serão excluídos!", "Confirmar",JOptionPane.OK_CANCEL_OPTION, 
            JOptionPane.QUESTION_MESSAGE); 
            System.out.println(x);
            
            if(x==0){
                Cliente cliente = modeloTabelaCliente.getCliente(linha);
                ClienteDAO dao = new ClienteDAO();
                
                try {
                    dao.delete(cliente);
                    modeloTabelaCliente.atualizarTabela();
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void searchClienteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchClienteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchClienteFieldActionPerformed

    private void btnNovoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoClienteMouseClicked
        // TODO add your handling code here:
        dialogNovoCliente.setVisible(true);
        dialogNovoCliente.toFront();
    }//GEN-LAST:event_btnNovoClienteMouseClicked

    private void fieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeClienteActionPerformed

    private void fieldRuaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRuaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRuaClienteActionPerformed

    private void btnCancelarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNovoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarNovoClienteActionPerformed

    private void btnCancelarNovoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarNovoClienteMouseClicked
        // TODO add your handling code here:
        dialogNovoCliente.dispose();
    }//GEN-LAST:event_btnCancelarNovoClienteMouseClicked

    private void btnGravarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarNovoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarNovoClienteActionPerformed

    private void btnGravarNovoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarNovoClienteMouseClicked
        // TODO add your handling code here:
        
        boolean formOk = true;
        String mensagem;
        mensagem = "Os seguintes campos estão inválidos: \n";
        
        //validar formulário
        if(fieldNomeCliente.getText().isEmpty()){
            mensagem += "Nome \n";
            formOk = false;
        }
        if(fieldTelefoneCliente.getText().trim().length() == 0 || fieldTelefoneCliente.getText().trim().length() > 13){
            mensagem += "Telefone \n";
            formOk = false;
        }
        
        if(fieldRuaCliente.getText().isEmpty()){
            mensagem += "Rua \n";
            formOk = false;
        }
        if(fieldNumeroCliente.getText().trim().length() == 0 || fieldNumeroCliente.getText().matches("-?\\d+(\\.\\d+)?") == false){
            mensagem += "Número \n";
            formOk = false;
            fieldNumeroCliente.setText("");
        }

        if(fieldBairroCliente.getText().isEmpty()){
            mensagem += "Bairro \n";
            formOk = false;
        }
        if(fieldCidadeCliente.getText().isEmpty()){
            mensagem += "Cidade \n";
            formOk = false;
        }
        
        if(!formOk){
            JOptionPane.showMessageDialog(dialogNovoCliente, mensagem, "Problemas encontrados",ERROR_MESSAGE);
        }
        else{
            //instancia um novo objeto do tipo cliente
            Cliente cliente = new Cliente();

            //carrega os dados do formulário para dentro do objeto cliente
            cliente.setNome(fieldNomeCliente.getText());
            cliente.setTelefone(fieldTelefoneCliente.getText());
            cliente.setRua(fieldRuaCliente.getText());
            cliente.setNumero(Integer.parseInt(fieldNumeroCliente.getText()));
            cliente.setComplemento(fieldComplementoCliente.getText());
            cliente.setBairro(fieldBairroCliente.getText());
            cliente.setCidade(fieldCidadeCliente.getText());
        
            //instancia um objeto da classe ClienteDAO

            try{
                ClienteDAO dao = new ClienteDAO();
                //tenta gravar os dados no banco de dados
                dao.insert(cliente);
            }
            catch (RuntimeException ex) {
                JOptionPane.showMessageDialog(dialogNovoCliente,"Erro ao gravar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            fieldNomeCliente.setText("");
            fieldTelefoneCliente.setText("");
            fieldRuaCliente.setText("");
            fieldNumeroCliente.setText("");
            fieldComplementoCliente.setText("");
            fieldBairroCliente.setText("");
            fieldCidadeCliente.setText("");

            //emite alerta de acordo com o resultado da operação
            JOptionPane.showMessageDialog(dialogNovoCliente, "Cliente cadastrado com sucesso!", "",INFORMATION_MESSAGE);
            dialogNovoCliente.dispose();

            modeloTabelaCliente.adicionaCliente(cliente);
        }
        
        

    }//GEN-LAST:event_btnGravarNovoClienteMouseClicked

    private void fieldNumeroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroClienteActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        int linha = tabelaClientes.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione um cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            exibirFormularioEditarCliente(modeloTabelaCliente.getCliente(linha));
        }

    }//GEN-LAST:event_jButton6MouseClicked

    private void fieldNomeClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeClienteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeClienteEditarActionPerformed

    private void fieldRuaClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRuaClienteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRuaClienteEditarActionPerformed

    private void btnGravarEditarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarEditarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarEditarClienteMouseClicked

    private void btnGravarEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarEditarClienteActionPerformed
        // TODO add your handling code here:
         boolean formOk = true;
        String mensagem;
        mensagem = "Os seguintes campos estão inválidos: \n";
        
        //validar formulário
        if(fieldNomeClienteEditar.getText().isEmpty()){
            mensagem += "Nome \n";
            formOk = false;
        }
        if(fieldTelefoneClienteEditar.getText().trim().length() == 0 || fieldTelefoneCliente.getText().trim().length() > 13){
            mensagem += "Telefone \n";
            formOk = false;
        }
        
        if(fieldRuaClienteEditar.getText().isEmpty()){
            mensagem += "Rua \n";
            formOk = false;
        }
        if(fieldNumeroClienteEditar.getText().trim().length() == 0 || fieldNumeroClienteEditar.getText().matches("-?\\d+(\\.\\d+)?") == false){
            mensagem += "Número \n";
            formOk = false;
            fieldNumeroClienteEditar.setText("");
        }

        if(fieldBairroClienteEditar.getText().isEmpty()){
            mensagem += "Bairro \n";
            formOk = false;
        }
        if(fieldCidadeClienteEditar.getText().isEmpty()){
            mensagem += "Cidade \n";
            formOk = false;
        }
        
        if(!formOk){
           JOptionPane.showMessageDialog(dialogEditarCliente, mensagem, "Problemas encontrados",ERROR_MESSAGE);
        }
        else{
            Cliente cliente = modeloTabelaCliente.getCliente(tabelaClientes.getSelectedRow());
            
            //carrega os dados do formulário para dentro do objeto cliente
            cliente.setNome(fieldNomeClienteEditar.getText());
            cliente.setTelefone(fieldTelefoneClienteEditar.getText());
            cliente.setRua(fieldRuaClienteEditar.getText());
            cliente.setNumero(Integer.parseInt(fieldNumeroClienteEditar.getText()));
            cliente.setComplemento(fieldComplementoClienteEditar.getText());
            cliente.setBairro(fieldBairroClienteEditar.getText());
            cliente.setCidade(fieldCidadeClienteEditar.getText());
        
            //instancia um objeto da classe ClienteDAO
             try{
                ClienteDAO dao = new ClienteDAO();
                //tenta gravar os dados no banco de dados
                dao.update(cliente);
                modeloTabelaCliente.fireTableDataChanged();
                JOptionPane.showMessageDialog(dialogEditarCliente, "Cliente alterado com sucesso!", "",INFORMATION_MESSAGE);
                dialogEditarCliente.dispose();
            }
            catch (RuntimeException ex) {
                JOptionPane.showMessageDialog(dialogNovoCliente,"Erro ao gravar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnGravarEditarClienteActionPerformed

    private void btnCancelarEditarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEditarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEditarClienteMouseClicked

    private void btnCancelarEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarClienteActionPerformed
        // TODO add your handling code here:
        dialogEditarCliente.dispose();
    }//GEN-LAST:event_btnCancelarEditarClienteActionPerformed

    private void fieldNumeroClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroClienteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroClienteEditarActionPerformed

    private void btnSearchClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClienteActionPerformed
        if (!(searchClienteField.getText().isEmpty())){
            ClienteDAO dao = new ClienteDAO();
            try {
                List<Cliente> lista = dao.findClientesByFilter(searchClienteField.getText());
                    modeloTabelaCliente.setLista(lista);
            } catch (IOException | SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSearchClienteActionPerformed

    private void btnClearFilterClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilterClienteActionPerformed
        ClienteDAO dao = new ClienteDAO();
        try {
            modeloTabelaCliente.setLista(dao.findAllClientes());
            searchClienteField.setText("");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClearFilterClienteActionPerformed

    private void valorPizzaSimplesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorPizzaSimplesKeyReleased
        // TODO add your handling code here      
       
    }//GEN-LAST:event_valorPizzaSimplesKeyReleased

    private void btnGravarValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarValoresActionPerformed
        // TODO add your handling code here:
        String mensagem = "Os seguintes Campos estão vazios ou incorretos: \n";
        Boolean gravar = true;
        
        if(valorPizzaSimples.getText().isEmpty() || !valorValido(valorPizzaSimples.getText())){
            mensagem += "Simples \n";
            gravar = false;
        }
        if(valorPizzaEspecial.getText().isEmpty() || !valorValido(valorPizzaEspecial.getText())){
            mensagem += "Especial \n";
            gravar = false;
        }
        if(valorPizzaPremium.getText().isEmpty() || !valorValido(valorPizzaPremium.getText())){
            mensagem += "Premium \n";
            gravar = false;
        }
        
        if(!gravar){
            JOptionPane.showMessageDialog(this, mensagem, "Problemas encontrados",ERROR_MESSAGE);
        }
        else{
            //instancia um novo objeto do tipo tipo de pizza
            TipoPizza tipopizza = new TipoPizza();

            //carrega os dados do formulário para dentro do objeto cliente
            
            if(!valorPizzaSimples.getText().isEmpty()){
                tipopizza.setValorCm(Double.parseDouble(valorPizzaSimples.getText()));
                tipopizza.setId(1);
                 try{
                TipoPizzaDAO dao = new TipoPizzaDAO();
                //tenta gravar os dados no banco de dados
                dao.update(tipopizza);
                }
                catch (RuntimeException ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao gravar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException | IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                //dialogNovoCliente.dispose();
                }
            if(!valorPizzaEspecial.getText().isEmpty()){
                tipopizza.setValorCm(Double.parseDouble(valorPizzaEspecial.getText()));
                tipopizza.setId(2);
                 try{
                TipoPizzaDAO dao = new TipoPizzaDAO();
                //tenta gravar os dados no banco de dados
                dao.update(tipopizza);
                }
                catch (RuntimeException ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao gravar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException | IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                //dialogNovoCliente.dispose();
                }
            if(!valorPizzaPremium.getText().isEmpty()){
                tipopizza.setValorCm(Double.parseDouble(valorPizzaPremium.getText()));
                tipopizza.setId(3);
                 try{
                TipoPizzaDAO dao = new TipoPizzaDAO();
                //tenta gravar os dados no banco de dados
                dao.update(tipopizza);
                }
                catch (RuntimeException ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao gravar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException | IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                //emite alerta de acordo com o resultado da operação
                JOptionPane.showMessageDialog(this, "Valor(es) atualizado(s) com sucesso!", "",INFORMATION_MESSAGE);
                //dialogNovoCliente.dispose();
                }
 
        }
        
    }//GEN-LAST:event_btnGravarValoresActionPerformed

    private void btnNovoSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoSaborActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNovoSaborActionPerformed

    private void btnNovoSaborMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoSaborMouseClicked
        // TODO add your handling code here:
        dialogNovoSabor.setVisible(true);
        dialogNovoSabor.toFront();
    }//GEN-LAST:event_btnNovoSaborMouseClicked

    private void fieldNomeSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeSaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeSaborActionPerformed

    private void btnGravarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarSaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarSaborActionPerformed

    private void fieldTipoSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTipoSaborActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fieldTipoSaborActionPerformed

    private void btnGravarSaborMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarSaborMouseClicked
        // TODO add your handling code here:
        boolean formOk = true;
        String mensagem;
        mensagem = "Os seguintes campos estão inválidos: \n";
        
        //validar formulário
        if(fieldNomeSabor.getText().isEmpty()){
            mensagem += "Nome \n";
            formOk = false;
        }
        
        
        
        if(!formOk){
            JOptionPane.showMessageDialog(dialogNovoSabor, mensagem, "Problemas encontrados",ERROR_MESSAGE);
        }
        else{
            //instancia um novo objeto do tipo cliente
            SaborPizza saborpizza = new SaborPizza();

            //carrega os dados do formulário para dentro do objeto cliente
            saborpizza.setNome(fieldNomeSabor.getText());
            saborpizza.setIngredientes(fieldIngredientesSabor.getText());
            if (null != fieldTipoSabor.getSelectedItem().toString())switch (fieldTipoSabor.getSelectedItem().toString()) {
                case "Simples":
                    saborpizza.setTipo(1);
                    break;
                case "Especial":
                    saborpizza.setTipo(2);
                    break;
                default:
                    saborpizza.setTipo(3);
                    break;
            }
            
            
            //instancia um objeto da classe ClienteDAO

            try{
                SaborPizzaDAO dao = new SaborPizzaDAO();
                //tenta gravar os dados no banco de dados
                dao.insert(saborpizza);
                modeloTabelaSabores.adicionaSabor(saborpizza);
            }
            catch (RuntimeException ex) {
                JOptionPane.showMessageDialog(dialogNovoSabor,"Erro ao gravar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            fieldNomeSabor.setText("");
            fieldIngredientesSabor.setText("");
            
            //emite alerta de acordo com o resultado da operação
            JOptionPane.showMessageDialog(dialogNovoSabor, "Sabor cadastrado com sucesso!", "",INFORMATION_MESSAGE);
            dialogNovoSabor.dispose();
        }
    }//GEN-LAST:event_btnGravarSaborMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dialogNovoSabor.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void abaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaPedidosMouseClicked
        try {
            // TODO add your handling code here:
            TipoPizzaDAO dao = new TipoPizzaDAO();
            valorPizzaSimples.setText(String.valueOf(dao.findValorByTipo(1)));
            valorPizzaEspecial.setText(String.valueOf(dao.findValorByTipo(2)));
            valorPizzaPremium.setText(String.valueOf(dao.findValorByTipo(3)));
            
            
        } catch (SQLException | IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abaPedidosMouseClicked
    
    public Boolean valorValido(String valor){
        try{
           Double d = Double.parseDouble(valor.replace(",", "."));
           return true && d>0;
          
        }
        catch(NumberFormatException e){
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaPedidos;
    private javax.swing.JButton btnCancelarEditarCliente;
    private javax.swing.JButton btnCancelarNovoCliente;
    private javax.swing.JButton btnClearFilterCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnGravarEditarCliente;
    private javax.swing.JButton btnGravarNovoCliente;
    private javax.swing.JButton btnGravarSabor;
    private javax.swing.JButton btnGravarValores;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnNovoSabor;
    private javax.swing.JButton btnSearchCliente;
    private javax.swing.JDialog dialogEditarCliente;
    private javax.swing.JDialog dialogNovoCliente;
    private javax.swing.JDialog dialogNovoSabor;
    private javax.swing.JDialog dialogValores;
    private javax.swing.JTextField fieldBairroCliente;
    private javax.swing.JTextField fieldBairroClienteEditar;
    private javax.swing.JTextField fieldCidadeCliente;
    private javax.swing.JTextField fieldCidadeClienteEditar;
    private javax.swing.JTextField fieldComplementoCliente;
    private javax.swing.JTextField fieldComplementoClienteEditar;
    private javax.swing.JTextArea fieldIngredientesSabor;
    private javax.swing.JTextField fieldNomeCliente;
    private javax.swing.JTextField fieldNomeClienteEditar;
    private javax.swing.JTextField fieldNomeSabor;
    private javax.swing.JTextField fieldNumeroCliente;
    private javax.swing.JTextField fieldNumeroClienteEditar;
    private javax.swing.JTextField fieldRuaCliente;
    private javax.swing.JTextField fieldRuaClienteEditar;
    private javax.swing.JTextField fieldTelefoneCliente;
    private javax.swing.JTextField fieldTelefoneClienteEditar;
    private javax.swing.JComboBox fieldTipoSabor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel labelBairroCliente;
    private javax.swing.JLabel labelBairroCliente1;
    private javax.swing.JLabel labelCidadeCliente;
    private javax.swing.JLabel labelCidadeCliente1;
    private javax.swing.JLabel labelComplementoCliente;
    private javax.swing.JLabel labelComplementoCliente1;
    private javax.swing.JLabel labelNomeCliente;
    private javax.swing.JLabel labelNomeCliente1;
    private javax.swing.JLabel labelNumeroCliente;
    private javax.swing.JLabel labelNumeroCliente1;
    private javax.swing.JLabel labelRuaCliente;
    private javax.swing.JLabel labelRuaCliente1;
    private javax.swing.JLabel labelTelefoneCliente;
    private javax.swing.JLabel labelTelefoneCliente1;
    private javax.swing.JTextField searchClienteField;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTextField valorPizzaEspecial;
    private javax.swing.JTextField valorPizzaPremium;
    private javax.swing.JTextField valorPizzaSimples;
    // End of variables declaration//GEN-END:variables
    public void exibirFormularioEditarCliente(Cliente cliente){
        fieldNomeClienteEditar.setText(cliente.getNome());
        fieldTelefoneClienteEditar.setText(cliente.getTelefone());
        fieldRuaClienteEditar.setText(cliente.getRua());
        fieldNumeroClienteEditar.setText(String.valueOf(cliente.getNumero()));
        fieldComplementoClienteEditar.setText(cliente.getComplemento());
        fieldBairroClienteEditar.setText(cliente.getBairro());
        fieldCidadeClienteEditar.setText(cliente.getCidade());
        
        dialogEditarCliente.setVisible(true);
        dialogEditarCliente.toFront();
        
    }
}

